// ── Types ──────────────────────────────────────────────
export interface SentinelCampaign {
  id: number;
  campaignId: string;
  title: string;
  dataOpsTotal: number | null;
  dataOpsValid: number | null;
  dataOpsInvalid: number | null;
  emailTotal: number | null;
  emailPending: number | null;
  emailValid: number | null;
  emailInvalid: number | null;
  qualityTotal: number | null;
  qualityPending: number | null;
  qualityValid: number | null;
  qualityInvalid: number | null;
  dbRefreshTotal: number | null;
  dbRefreshPending: number | null;
  dbRefreshValid: number | null;
  dbRefreshInvalid: number | null;
  vvTotal: number | null;
  vvPending: number | null;
  vvValid: number | null;
  vvInvalid: number | null;
  misTotal: number | null;
  misPending: number | null;
  misDelivered: number | null;
  misAccepted: number | null;
  misClientRejected: number | null;
  misRTD: number | null;
  misInternalRejected: number | null;
}

// ── Data ──────────────────────────────────────────────
export const sentinelCampaignData: SentinelCampaign[] = [
  {
    id: 1,
    campaignId: 'PV01_271025_0001_00001',
    title: 'Dell EMEA (25Q4) ISG MB GenAi BANT - UK - 50578',
    dataOpsTotal: 150,
    dataOpsValid: 120,
    dataOpsInvalid: 30,
    emailTotal: 120,
    emailPending: 10,
    emailValid: 100,
    emailInvalid: 10,
    qualityTotal: 100,
    qualityPending: null,
    qualityValid: 95,
    qualityInvalid: 5,
    dbRefreshTotal: null,
    dbRefreshPending: null,
    dbRefreshValid: null,
    dbRefreshInvalid: null,
    vvTotal: null,
    vvPending: null,
    vvValid: null,
    vvInvalid: null,
    misTotal: 90,
    misPending: 5,
    misDelivered: 80,
    misAccepted: 75,
    misClientRejected: 3,
    misRTD: 2,
    misInternalRejected: null,
  },
  {
    id: 2,
    campaignId: 'PV02_271025_0001_00002',
    title: 'HP APJ Storage Solutions - SG - 456',
    dataOpsTotal: 200,
    dataOpsValid: 180,
    dataOpsInvalid: 20,
    emailTotal: null,
    emailPending: null,
    emailValid: null,
    emailInvalid: null,
    qualityTotal: null,
    qualityPending: null,
    qualityValid: null,
    qualityInvalid: null,
    dbRefreshTotal: null,
    dbRefreshPending: null,
    dbRefreshValid: null,
    dbRefreshInvalid: null,
    vvTotal: null,
    vvPending: null,
    vvValid: null,
    vvInvalid: null,
    misTotal: null,
    misPending: null,
    misDelivered: null,
    misAccepted: null,
    misClientRejected: null,
    misRTD: null,
    misInternalRejected: null,
  },
  {
    id: 3,
    campaignId: 'PV01_271025_0002_00003',
    title: 'Cisco EMEA Security - DE - 789',
    dataOpsTotal: 300,
    dataOpsValid: 270,
    dataOpsInvalid: 30,
    emailTotal: 270,
    emailPending: 20,
    emailValid: 240,
    emailInvalid: 10,
    qualityTotal: 240,
    qualityPending: 15,
    qualityValid: 210,
    qualityInvalid: 15,
    dbRefreshTotal: 210,
    dbRefreshPending: 10,
    dbRefreshValid: 195,
    dbRefreshInvalid: 5,
    vvTotal: null,
    vvPending: null,
    vvValid: null,
    vvInvalid: null,
    misTotal: null,
    misPending: null,
    misDelivered: null,
    misAccepted: null,
    misClientRejected: null,
    misRTD: null,
    misInternalRejected: null,
  },
  {
    id: 4,
    campaignId: 'PV03_271025_0001_00004',
    title: 'Microsoft Azure - US - 321',
    dataOpsTotal: null,
    dataOpsValid: null,
    dataOpsInvalid: null,
    emailTotal: null,
    emailPending: null,
    emailValid: null,
    emailInvalid: null,
    qualityTotal: null,
    qualityPending: null,
    qualityValid: null,
    qualityInvalid: null,
    dbRefreshTotal: null,
    dbRefreshPending: null,
    dbRefreshValid: null,
    dbRefreshInvalid: null,
    vvTotal: null,
    vvPending: null,
    vvValid: null,
    vvInvalid: null,
    misTotal: null,
    misPending: null,
    misDelivered: null,
    misAccepted: null,
    misClientRejected: null,
    misRTD: null,
    misInternalRejected: null,
  },
  {
    id: 5,
    campaignId: 'PV04_271025_0001_00005',
    title: 'IBM Cloud APAC - AU - 654',
    dataOpsTotal: 80,
    dataOpsValid: 70,
    dataOpsInvalid: 10,
    emailTotal: null,
    emailPending: null,
    emailValid: null,
    emailInvalid: null,
    qualityTotal: null,
    qualityPending: null,
    qualityValid: null,
    qualityInvalid: null,
    dbRefreshTotal: null,
    dbRefreshPending: null,
    dbRefreshValid: null,
    dbRefreshInvalid: null,
    vvTotal: null,
    vvPending: null,
    vvValid: null,
    vvInvalid: null,
    misTotal: null,
    misPending: null,
    misDelivered: null,
    misAccepted: null,
    misClientRejected: null,
    misRTD: null,
    misInternalRejected: null,
  },
  {
    id: 6,
    campaignId: 'PV02_271025_0002_00006',
    title: 'Oracle EMEA DB - FR - 987',
    dataOpsTotal: null,
    dataOpsValid: null,
    dataOpsInvalid: null,
    emailTotal: null,
    emailPending: null,
    emailValid: null,
    emailInvalid: null,
    qualityTotal: null,
    qualityPending: null,
    qualityValid: null,
    qualityInvalid: null,
    dbRefreshTotal: null,
    dbRefreshPending: null,
    dbRefreshValid: null,
    dbRefreshInvalid: null,
    vvTotal: null,
    vvPending: null,
    vvValid: null,
    vvInvalid: null,
    misTotal: null,
    misPending: null,
    misDelivered: null,
    misAccepted: null,
    misClientRejected: null,
    misRTD: null,
    misInternalRejected: null,
  },
  {
    id: 7,
    campaignId: 'PV02_271025_0002_00006',
    title: 'Oracle EMEA DB - FR - 987',
    dataOpsTotal: null,
    dataOpsValid: null,
    dataOpsInvalid: null,
    emailTotal: null,
    emailPending: null,
    emailValid: null,
    emailInvalid: null,
    qualityTotal: null,
    qualityPending: null,
    qualityValid: null,
    qualityInvalid: null,
    dbRefreshTotal: null,
    dbRefreshPending: null,
    dbRefreshValid: null,
    dbRefreshInvalid: null,
    vvTotal: null,
    vvPending: null,
    vvValid: null,
    vvInvalid: null,
    misTotal: null,
    misPending: null,
    misDelivered: null,
    misAccepted: null,
    misClientRejected: null,
    misRTD: null,
    misInternalRejected: null,
  },
  {
    id: 8,
    campaignId: 'PV02_271025_0002_00006',
    title: 'Oracle EMEA DB - FR - 987',
    dataOpsTotal: null,
    dataOpsValid: null,
    dataOpsInvalid: null,
    emailTotal: null,
    emailPending: null,
    emailValid: null,
    emailInvalid: null,
    qualityTotal: null,
    qualityPending: null,
    qualityValid: null,
    qualityInvalid: null,
    dbRefreshTotal: null,
    dbRefreshPending: null,
    dbRefreshValid: null,
    dbRefreshInvalid: null,
    vvTotal: null,
    vvPending: null,
    vvValid: null,
    vvInvalid: null,
    misTotal: null,
    misPending: null,
    misDelivered: null,
    misAccepted: null,
    misClientRejected: null,
    misRTD: null,
    misInternalRejected: null,
  },
  {
    id: 9,
    campaignId: 'PV02_271025_0002_00006',
    title: 'Oracle EMEA DB - FR - 987',
    dataOpsTotal: null,
    dataOpsValid: null,
    dataOpsInvalid: null,
    emailTotal: null,
    emailPending: null,
    emailValid: null,
    emailInvalid: null,
    qualityTotal: null,
    qualityPending: null,
    qualityValid: null,
    qualityInvalid: null,
    dbRefreshTotal: null,
    dbRefreshPending: null,
    dbRefreshValid: null,
    dbRefreshInvalid: null,
    vvTotal: null,
    vvPending: null,
    vvValid: null,
    vvInvalid: null,
    misTotal: null,
    misPending: null,
    misDelivered: null,
    misAccepted: null,
    misClientRejected: null,
    misRTD: null,
    misInternalRejected: null,
  },
  {
    id: 10,
    campaignId: 'PV02_271025_0002_00006',
    title: 'Oracle EMEA DB - FR - 987',
    dataOpsTotal: null,
    dataOpsValid: null,
    dataOpsInvalid: null,
    emailTotal: null,
    emailPending: null,
    emailValid: null,
    emailInvalid: null,
    qualityTotal: null,
    qualityPending: null,
    qualityValid: null,
    qualityInvalid: null,
    dbRefreshTotal: null,
    dbRefreshPending: null,
    dbRefreshValid: null,
    dbRefreshInvalid: null,
    vvTotal: null,
    vvPending: null,
    vvValid: null,
    vvInvalid: null,
    misTotal: null,
    misPending: null,
    misDelivered: null,
    misAccepted: null,
    misClientRejected: null,
    misRTD: null,
    misInternalRejected: null,
  },
  {
    id: 11,
    campaignId: 'PV02_271025_0002_00006',
    title: 'Oracle EMEA DB - FR - 987',
    dataOpsTotal: null,
    dataOpsValid: null,
    dataOpsInvalid: null,
    emailTotal: null,
    emailPending: null,
    emailValid: null,
    emailInvalid: null,
    qualityTotal: null,
    qualityPending: null,
    qualityValid: null,
    qualityInvalid: null,
    dbRefreshTotal: null,
    dbRefreshPending: null,
    dbRefreshValid: null,
    dbRefreshInvalid: null,
    vvTotal: null,
    vvPending: null,
    vvValid: null,
    vvInvalid: null,
    misTotal: null,
    misPending: null,
    misDelivered: null,
    misAccepted: null,
    misClientRejected: null,
    misRTD: null,
    misInternalRejected: null,
  },
  {
    id: 12,
    campaignId: 'PV02_271025_0002_00006',
    title: 'Oracle EMEA DB - FR - 987',
    dataOpsTotal: null,
    dataOpsValid: null,
    dataOpsInvalid: null,
    emailTotal: null,
    emailPending: null,
    emailValid: null,
    emailInvalid: null,
    qualityTotal: null,
    qualityPending: null,
    qualityValid: null,
    qualityInvalid: null,
    dbRefreshTotal: null,
    dbRefreshPending: null,
    dbRefreshValid: null,
    dbRefreshInvalid: null,
    vvTotal: null,
    vvPending: null,
    vvValid: null,
    vvInvalid: null,
    misTotal: null,
    misPending: null,
    misDelivered: null,
    misAccepted: null,
    misClientRejected: null,
    misRTD: null,
    misInternalRejected: null,
  },
];